version: '3.3'
services:
  discovery:
    image: discovery:latest
    ports:
      - 8761:8761
  api-gateway:
    image: api-gateway:latest
    ports:
      - 8080:8080
    depends_on:
      - discovery
  user-service:
    image: user-service:latest
    ports:
      - 8090:8090