spring:
  application:
    name: api-gateway
  data:
    mongodb:
      uri: mongodb+srv://streamster:${MONGO_PASSWORD}@streamster.mysoh.gcp.mongodb.net/streamster
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: https://user-service-ayoqp7z2fq-lz.a.run.app/user-service
          predicates:
            - Path=/user-service/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
        - id: video-service-route
          uri: https://video-service-ayoqp7z2fq-lz.a.run.app/user-service
          predicates:
            - Path=/video-service/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
#        - id: search-service-route
#          uri: lb://search-service
#          predicates:
#            - Path=/search-service/**
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Origin
#        - id: lists-service-route
#          uri: lb://lists-service
#          predicates:
#            - Path=/lists-service/**
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Origin
#        - id: lists-service-route
#          uri: lb://recommendation-service
#          predicates:
#            - Path=/recommendation-service/**
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Origin
server:
  port: 8080