spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://streamster:22noRhzBxqErEMTc@streamster.mysoh.gcp.mongodb.net/streamster
server:
  servlet:
    context-path: /user-service
  port: 8080
swagger:
  config:
    refreshrate: 60000