spring:
  application:
    name: user-service
  data:
    mongodb:
      #     change to your computer ip
      host: 10.10.11.252
      port: 27017
      database: filmMaster
server:
  servlet:
    context-path: /user-service
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
swagger:
  config:
    refreshrate: 60000
