spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://streamster:${MONGO_PASSWORD}@streamster.mysoh.gcp.mongodb.net/streamster
  rabbitmq:
    addresses: amqps://usungdnh:${RABBIT_PASSWORD}@kangaroo.rmq.cloudamqp.com/usungdnh
server:
  servlet:
    context-path: /user-service
  port: 8080
swagger:
  config:
    refreshrate: 60000

services:
  user: https://user-service-ayoqp7z2fq-lz.a.run.app
  search: http://localhost:8091/search-service
  recommendation: http://localhost:8092/recommendation-service
  video: https://video-service-ayoqp7z2fq-lz.a.run.app