spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://streamster:${MONGO_PASSWORD}@streamster.mysoh.gcp.mongodb.net/streamster
  rabbitmq:
    addresses: amqps://usungdnh:${RABBIT_PASSWORD}@kangaroo.rmq.cloudamqp.com/usungdnh
server:
  servlet:
    context-path: /user-service
  port: 8090
swagger:
  config:
    refreshrate: 60000

services:
  user: http://localhost:8090/user-service
  search: http://localhost:8091/search-service
  recommendation: http://localhost:8092/recommendation-service
  video: http://localhost:8093/video-service
