spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb+srv://streamster:${MONGO_PASSWORD}@streamster.mysoh.gcp.mongodb.net/streamster
    neo4j:
      uri: bolt://neo4j:${NEO_PASSWORD}@35.228.122.172:7687
  rabbitmq:
    addresses: amqps://usungdnh:${RABBIT_PASSWORD}@kangaroo.rmq.cloudamqp.com/usungdnh

security:
  oauth2:
    resource:
      filter-order: 3
      preferTokenInfo: true
      token-info-uri: http://localhost:8080/user-service/oauth/check_token
    client:
      client-id: my-trusted-client
      client-secret: secret

server:
  servlet:
    context-path: /search-service
  port: 8091

services:
  user: http://localhost:8090/user-service
  search: http://localhost:8091/search-service
  recommendation: http://localhost:8092/recommendation-service
  video: http://localhost:8093/video-service
