spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb+srv://streamster:22noRhzBxqErEMTc@streamster.mysoh.gcp.mongodb.net/streamster
security:
  oauth2:
    resource:
      filter-order: 3
      preferTokenInfo: true
      token-info-uri: http://localhost:8080/user-service/oauth/check_token
    client:
      client-id: my-trusted-client
      client-secret: secret

server:
  servlet:
    context-path: /search-service
